# Global values for all subcharts
global: {}

# Configuration for marketing-webpage subchart
marketing-webpage:
  enabled: true  
  image:
    repository: ghcr.io/noahy-schmid
    tag: "test"
  
  service:
    type: ClusterIP
    port: 80
  
  ingress:
    path: /test
