name: PR Cleanup

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install sshpass and setup SSH
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts
          
      - name: Cleanup PR preview
        env:
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
        run: |
          # Check if cleanup script exists and run it
          sshpass -p "$DROPLET_PASSWORD" ssh $DROPLET_USER@$DROPLET_HOST "
            if [ -f ~/cleanup-pr.sh ]; then
              sudo ~/cleanup-pr.sh ${{ github.event.number }}
            else
              echo 'Cleanup script not found, performing manual cleanup...'
              sudo rm -rf /var/www/pr-${{ github.event.number }} || true
              echo 'PR directory removed'
            fi
          "
          
      - name: Comment PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧹 **PR Preview Cleaned Up**
              
              The preview deployment for this PR has been removed from the server.`
            })
