name: PR Cleanup

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install sshpass and setup SSH
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts
          
      - name: Cleanup PR preview
        env:
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          sshpass -p "$DROPLET_PASSWORD" ssh $DROPLET_USER@$DROPLET_HOST "
            # Stop and remove the PR container
            docker stop pr-$PR_NUMBER-service || echo 'Container not running'
            docker rm pr-$PR_NUMBER-service || echo 'Container not found'
            
            # Remove the Docker image (optional, saves space)
            docker rmi ghcr.io/${{ github.repository_owner }}/my-services:$PR_NUMBER || echo 'Image not found locally'
            
            # Remove NGINX configuration
            sudo rm -f /etc/nginx-docker/pr-deployments/pr-$PR_NUMBER.conf || true
            
            # Reload NGINX to remove the configuration
            docker exec nginx-proxy nginx -s reload || echo 'Failed to reload NGINX'
            
            echo 'PR #$PR_NUMBER cleanup completed'
          "
          
      - name: Comment PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧹 **PR Preview Cleaned Up**
              
              The preview deployment for this PR has been removed from the server.`
            })
